import type { Metadata } from "next";
import { Geist, Geist_Mono, Saira, Saira_Condensed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

const sairaCondensed = Saira_Condensed({
  variable: "--font-saira-condensed",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "RAP Kology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${saira.variable} ${sairaCondensed.variable} antialiased `}
      >
        <Header />
        <div className="max-w-[1440px] mx-auto ">{children}</div>
      </body>
    </html>
  );
}
